//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webshop.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Articles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Articles() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Webshop.Resources.Articles", typeof(Articles).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Aktiv.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Artikelnamn.
        /// </summary>
        public static string ArticleName {
            get {
                return ResourceManager.GetString("ArticleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tillverkare.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Kampanj.
        /// </summary>
        public static string Campaign {
            get {
                return ResourceManager.GetString("Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Kategori.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Beskrivning.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Fältet får inte vara tomt.
        /// </summary>
        public static string ErrorArticleDescription {
            get {
                return ResourceManager.GetString("ErrorArticleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Fältet får inte vara tomt.
        /// </summary>
        public static string ErrorArticleName {
            get {
                return ResourceManager.GetString("ErrorArticleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Fältet får inte vara tomt.
        /// </summary>
        public static string ErrorArticlePrice {
            get {
                return ResourceManager.GetString("ErrorArticlePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Fältet får inte vara tomt.
        /// </summary>
        public static string ErrorArticleStock {
            get {
                return ResourceManager.GetString("ErrorArticleStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Fältet får inte vara tomt.
        /// </summary>
        public static string ErrorCategoryName {
            get {
                return ResourceManager.GetString("ErrorCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Fältet får inte vara tomt.
        /// </summary>
        public static string ErrorProductdata {
            get {
                return ResourceManager.GetString("ErrorProductdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Fältet får inte vara tomt.
        /// </summary>
        public static string ErrorProductName {
            get {
                return ResourceManager.GetString("ErrorProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Fältet får inte vara tomt.
        /// </summary>
        public static string ErrorSubCategory {
            get {
                return ResourceManager.GetString("ErrorSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Fältet får inte vara tomt.
        /// </summary>
        public static string ErrorVendorName {
            get {
                return ResourceManager.GetString("ErrorVendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Produktdata 1.
        /// </summary>
        public static string Feature1 {
            get {
                return ResourceManager.GetString("Feature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Produktdata 2.
        /// </summary>
        public static string Feature2 {
            get {
                return ResourceManager.GetString("Feature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Produktdata 3.
        /// </summary>
        public static string Feature3 {
            get {
                return ResourceManager.GetString("Feature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Produktdata 4.
        /// </summary>
        public static string Feature4 {
            get {
                return ResourceManager.GetString("Feature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ballan Allan.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Pris.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Produktyp.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Lagerstatus.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Underkategori.
        /// </summary>
        public static string SubCategoryType {
            get {
                return ResourceManager.GetString("SubCategoryType", resourceCulture);
            }
        }
    }
}
